logging:
    level:
        root: INFO

spring:
    application:
        name: notification-service

    datasource:
#        driver-class-name: org.postgresql.Driver
        url: ${DATABASE_URL}
        username: ${DATABASE_USERNAME}
        password: ${DATABASE_PASSWORD}
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true

    rabbitmq:
        host: ${RABBITMQ_HOST}
        port: ${RABBITMQ_PORT}
        username: ${RABBITMQ_USERNAME}
        password: ${RABBITMQ_PASSWORD}

        retry-queues-ttl: 2000
        retry-max-count: 3

        notification:
            queue: "notification-queue"
            exchange: "notification-exchange"
            routing-key: "notification-key"

        retry-notification:
            queue: "retry-notification-queue"
            exchange: "retry-notification-exchange"
            routing-key: "retry-notification-key"

        dead-letter:
            queue: "dead-queue"
            exchange: "dead-exchange"
            routing-key: "dead-key"

#eureka:
#    client:
#        service-url:
#            default-zone: ${REGISTRY_SERVICE_URL}
#        healthcheck:
#            enabled: true
#    instance:
#        lease-expiration-duration-in-seconds: 2
#        lease-renewal-interval-in-seconds: 1

server:
    port: ${PORT}